inherit_from: .rubocop_todo.yml

Style/StringLiterals:
  Exclude:
    - db/schema.rb

Style/WordArray:
  Exclude:
    - db/schema.rb

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  CountAsOne: ['array', 'hash']
  CountComments: false
  Exclude:
    - spec/**/*
    - lib/tasks/**/*
    - config/**/*
    - db/schema.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - db/schema.rb
    - db/migrate/**

Metrics/ClassLength:
  CountAsOne: ['array', 'hash']
  CountComments: false

Metrics/MethodLength:
  CountAsOne: ['array', 'hash']
  CountComments: false
  Exclude:
    - spec/**/*
